apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-kafka.fullname" . }}
  labels:
    app: {{ template "cp-kafka.name" . }}
    chart: {{ template "cp-kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 9092
      name: broker
  selector:
    app: {{ template "cp-kafka.name" . }}
    release: {{ .Release.Name }}