{
 "title": "CombinedDashboardOrangePink",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Kafka Brokers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PINK  ------------------------------  ORANGE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(cp_kafka_server_replicamanager_leadercount)"
    },
    {
     "expr": "count(cp_kafka_server_replicamanager_leadercount)"
    }
   ]
  },
  {
   "title": "PINK ------------------------------  ORANGE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(cp_kafka_controller_kafkacontroller_activecontrollercount)"
    },
    {
     "expr": "sum(cp_kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "PINK  ------------------------------  ORANGE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(cp_kafka_controller_controllerstats_uncleanleaderelectionspersec)"
    },
    {
     "expr": "sum(cp_kafka_controller_controllerstats_uncleanleaderelectionspersec)"
    }
   ]
  },
  { "title": "Partition Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "PINK  ------------------------------  ORANGE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(cp_kafka_server_replicamanager_underreplicatedpartitions)"
    },
    {
     "expr": "sum(cp_kafka_server_replicamanager_underreplicatedpartitions)"
    }
   ]
  },
  {
   "title": "PINK  ------------------------------  ORANGE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum(cp_kafka_server_replicamanager_underreplicatedpartitions)"
    },
    {
     "expr": "sum(cp_kafka_server_replicamanager_underreplicatedpartitions)"
    }
   ]
  },
  {
   "title": "PINK  ------------------------------  ORANGE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(cp_kafka_server_replicamanager_partitioncount)"
    },
    {
     "expr": "sum(cp_kafka_server_replicamanager_partitioncount)"
    }
   ]
  },
  { "title": "Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "ZK Quorum Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "avg(cp_zookeeper_quorumsize{release=~\"cp-zookeeper\"})"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "targets": [
    {
     "expr": "sum(cp_zookeeper_numaliveconnections)"
    }
   ]
  },
  {
   "title": "Number of ZNodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "avg(cp_zookeeper_inmemorydatatree_nodecount)"
    }
   ]
  },
  {
   "title": "Number of Watchers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "sum(cp_zookeeper_inmemorydatatree_watchcount{release=~\"cp-zookeeper\"})"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_zookeeper_outstandingrequests",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Request Latency - AVERAGE",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cp_zookeeper_avgrequestlatency", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Request Latency - MINIMUM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cp_zookeeper_minrequestlatency", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Request Latency - MAXIMUM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cp_zookeeper_maxrequestlatency", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  { "title": "Kafka Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Byte Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_bytesinpersec{release=~\"cp-kafka\"})",
     "legendFormat": "Incoming Byte Rate-Pink"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_bytesinpersec{release=~\"cp-kafka\"})",
     "legendFormat": "Incoming Byte Rate-Orange"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_bytesoutpersec{release=~\"cp-kafka\"})",
     "legendFormat": "Outgoing Byte Rate Pink"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_bytesoutpersec{release=~\"cp-kafka\"})",
     "legendFormat": "Outgoing Byte Rate Orange"
    }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_messagesinpersec)",
     "legendFormat": "Message per Second -Pink"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_messagesinpersec)",
     "legendFormat": "Message per Second -Orange"
    }
   ]
  },
  {
   "title": "Produce Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_totalproducerequestspersec)",
     "legendFormat": "Producer Request Rate -Pink"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_totalproducerequestspersec)",
     "legendFormat": "Producer Request Rate -Orange"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_failedproducerequestspersec)",
     "legendFormat": "Failed Produce Request Rate -Pink"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_failedproducerequestspersec)",
     "legendFormat": "Failed Produce Request Rate -Orange"
    }
   ]
  },
  {
   "title": "Fetch Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_totalfetchrequestspersec)",
     "legendFormat": "Fetch Request Rate -Pink"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_totalfetchrequestspersec)",
     "legendFormat": "Fetch Request Rate -Orange"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_failedfetchrequestspersec)",
     "legendFormat": "Failed Fetch Request Rate -Pink"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_failedfetchrequestspersec)",
     "legendFormat": "Failed Fetch Request Rate -Orange"
    }
   ]
  },
  { "title": "Pod Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{pod=~\"cp-kafka-(\\\\d+)\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}-pink"
    },
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{pod=~\"cp-kafka-(\\\\d+)\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}-orange"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"cp-kafka-(\\\\d+)\"}) by (pod)",
     "legendFormat": "{{pod}}-pink"
    },
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"cp-kafka-(\\\\d+)\"}) by (pod)",
     "legendFormat": "{{pod}}-orange"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"datadir-0-cp-kafka.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}-pink"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"datadir-0-cp-kafka.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}-orange"
    }
   ]
  },
  {
   "title": "Network Proc Avg Idle Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_network_socketserver_networkprocessoravgidlepercent*100",
     "legendFormat": "{{kubernetes_pod_name}}-pink"
    },
    {
     "expr": "cp_kafka_network_socketserver_networkprocessoravgidlepercent*100",
     "legendFormat": "{{kubernetes_pod_name}}-orange"
    }
   ]
  }
 ]
}